apiVersion: apps/v1
kind: Deployment
metadata:
  name: jena-demo-source
spec:
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0  
  template:
    spec:
      restartPolicy: Always
      containers:
        - name: jena-demo-source
          image: 712440397331.dkr.ecr.ap-northeast-2.amazonaws.com/jena-demo-ecr
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            requests:
              cpu: "10m"
              memory: "400Mi"
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 20"]
          env:
            - name: ENV
              value: "DEV"                
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: jena-demo-source
              topologyKey: kubernetes.io/hostname
            weight: 100   
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - ops
      tolerations:
        - effect: NoSchedule
          key: role
          operator: Equal
          value: ops