apiVersion: apps/v1
kind: Deployment
metadata:
  name: jena-demo-source
spec:
  revisionHistoryLimit: 5
  minReadySeconds: 10
  # Graceful Shutdown 설정
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      restartPolicy: Always
      containers:
        - name: jena-demo-source
          image: 712440397331.dkr.ecr.ap-northeast-2.amazonaws.com/jena-demo-ecr
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            protocol: TCP
          # QoS 타입 Guaranteed  
          resources:
            limits:
              cpu: 1
              memory: 1.5Gi
            requests:
              cpu: 1
              memory: 1.5Gi
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false          
          # Graceful Shutdown 설정               
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 20"]             
          # ENV 설정      
          env:
          - name: ENV
            value: "DEV"
      # 스케줄링 설정                       
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: jena-demo-source
              topologyKey: kubernetes.io/hostname
            weight: 100   
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - ops
      tolerations:
        - effect: NoSchedule
          key: role
          operator: Equal
          value: ops