apiVersion: apps/v1
kind: Deployment
metadata:
  name: jena-demo-source
spec:
  # minReadySeconds: 10
  # # Graceful Shutdown 설정
  # strategy:
  #   type: RollingUpdate
  #   rollingUpdate:
  #     maxSurge: 1
  #     maxUnavailable: 0  
  template:
    spec:
      restartPolicy: Always
      containers:
        - name: jena-demo-source
          image: 712440397331.dkr.ecr.ap-northeast-2.amazonaws.com/jena-demo-ecr
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            protocol: TCP
          # QoS 타입 Guaranteed  
          resources:
            limits:
              cpu: "10m"
              memory: "400Mi"            
            requests:
              cpu: "10m"
              memory: "400Mi"
          # Health Check    
          # livenessProbe:
          #   httpGet:
          #     path: /actuator/health/liveness
          #     port: 8080
          #   initialDelaySeconds: 60
          #   periodSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     path: /actuator/health/readiness
          #     port: 8080
          #   initialDelaySeconds: 30
          #   periodSeconds: 30
          #   failureThreshold: 3
          #   successThreshold: 1
          #   timeoutSeconds: 5            
          # Graceful Shutdown 설정                 
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 20"]
          # ENV 설정      
          # env:
          #   - name: ENV
          #     value: "DEV"
      # 스케줄링 설정                       
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: jena-demo-source
              topologyKey: kubernetes.io/hostname
            weight: 100   
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - ops
      tolerations:
        - effect: NoSchedule
          key: role
          operator: Equal
          value: ops