apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: jena-demo-source
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jena-demo-source
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - resource:
      name: memory
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource